-- Add up migration script her
CREATE TABLE"user"(
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL  PRIMARY KEY,
email VARCHAR(128) UNIQUE,
verified_email BOOLEAN DEFAULT FALSE,
name VARCHAR(128),
given_name VARCHAR(128),
family_name VARCHAR(128),
picture VARCHAR(128),
locale VARCHAR(128)
);
