[env]
PORT = "3000"
DATABASE_URL = "postgres://postgres@localhost/axum_tut"
GOOGLE_CLIENT_ID = "509685768975-d8ptrledssua28busdejfvqv5k812b8q.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
GOOLE_REDIRECT = "http://localhost:3000/api/auth/google-login"
JWT_SECRET = "LOXZkDGny4fiYO0zu17dr4RuuSpSUYbr"
